services:
  postgres-dev:
    image: postgres:16-alpine
    container_name: postgres-dev
    restart: unless-stopped

    env_file:
      - .env.dev

    ports:
      - "5431:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - sif-net-dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq-dev:
    image: rabbitmq:3.13-management
    container_name: rabbitmq-dev
    restart: unless-stopped

    env_file:
      - .env.dev

    ports:
      - "5672:5672"     # AMQP
      - "15672:15672"   # Management UI

    networks:
      - sif-net-dev

    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio-dev:
    image: minio/minio:latest
    container_name: minio-dev
    ports:
      - "9000:9000"  # API S3
      - "9001:9001"  # Console web
    volumes:
      - minio_data:/data
    env_file:
      - .env.dev
    networks:
      - sif-net-dev
    command: server /data --console-address ":9001"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3

  minio-setup-dev:
    image: minio/mc:latest
    container_name: minio-setup-dev
    depends_on:
      minio-dev:
        condition: service_healthy
    networks:
      - sif-net-dev
    entrypoint: >
      /bin/sh -c "
        mc alias set local http://minio-dev:9000 minioadmin minioadmin &&
        mc mb --ignore-existing local/sif-dev &&
        mc anonymous set public local/sif-dev
      "
  
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: sif-dev:latest
    ports:
      - "3333:3333"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - sif-net-dev
    env_file:
      - .env.dev
    restart: unless-stopped
    depends_on:
      postgres-dev:
          condition: service_healthy
      rabbitmq-dev:
          condition: service_healthy
      minio-dev:
          condition: service_healthy
    command: npm run dev

volumes:
  postgres_data:
  rabbitmq_data:
  minio_data:

networks:
  sif-net-dev:
    driver: bridge