services:
  postgres-dev:
    image: postgres:16-alpine
    container_name: postgres-dev
    restart: unless-stopped

    env_file:
      - .env.dev

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - sif-net-dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq-dev:
    image: rabbitmq:3.13-management
    container_name: rabbitmq-dev
    restart: unless-stopped

    env_file:
      - .env.dev

    ports:
      - "5672:5672"     # AMQP
      - "15672:15672"   # Management UI

    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}

    networks:
      - sif-net-dev

    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: sif-dev:latest
    ports:
      - "3333:3333"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - sif-net-dev
    env_file:
      - .env.dev
    restart: unless-stopped
    depends_on:
      postgres-dev:
          condition: service_healthy
      rabbitmq-dev:
          condition: service_healthy
    command: npm run dev

volumes:
  postgres_data:
  rabbitmq_data:

networks:
  sif-net-dev:
    driver: bridge