export const REQUEST_STATUS = {
	PENDING: "PENDING",
	APPROVED: "APPROVED",
	REJECTED: "REJECTED",
	COMPLETED: "COMPLETED",
} as const;

export const REQUEST_STATUSES = [
	REQUEST_STATUS.PENDING,
	REQUEST_STATUS.APPROVED,
	REQUEST_STATUS.REJECTED,
	REQUEST_STATUS.COMPLETED,
] as const;
export type requestStatuses = (typeof REQUEST_STATUSES)[number];
