export const AUDIT_ACTIONS = [
	"USER.CREATED",
	"USER.UPDATED",
	"USER.DELETED",
	"VEHICLE.CREATED",
	"VEHICLE.UPDATED",
	"VEHICLE.DELETED",
	"REQUEST.CREATED",
	"REQUEST.APPROVED",
	"REQUEST.REJECTED",
	"TRIP.STARTED",
	"TRIP.FINISHED",
] as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[number];
