name: Core Service CI

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main
      - develop

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    env:
      POSTGRES_USER: postgres-dev
      POSTGRES_PASSWORD: postgres-dev
      POSTGRES_DB: sif-dev
      JWT_SECRET: test_secret

      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_HOST: minio-dev
      MINIO_BUCKET: sif_dev

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.14
          cache: npm

      - name: Instalar dependências
        run: npm ci

      - name: Rodar testes
        run: npm run test

      - name: Verificar build
        run: npm run build

      - name: Verificar lint
        run: npm run lint
