name: Core Service CI

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main
      - develop

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_db
          JWT_SECRET: test_secret
          RABBITMQ_DEFAULT_USER: test_user
          RABBITMQ_DEFAULT_PASS: test_password
          MINIO_ROOT_USER: test_user
          MINIO_ROOT_PASSWORD: test_password
          MINIO_HOST: localhost
          MINIO_BUCKET: test_bucket

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.14
          cache: npm

      - name: Instalar dependências
        run: npm ci

      - name: Rodar testes
        run: npm run test

      - name: Verificar lint
        run: npm run lint